server:
  port: 3001

spring:
  application:
    name: auth-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: auth_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
    instance:
      lease-renewal-interval-in-seconds: 2
      lease-expiration-duration-in-seconds: 5
      prefer-ip-address: true
      health-check-url-path: /actuator/health
      status-page-url-path: /actuator/info

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 